rom_config: '../../../ph_usa/config.yaml'
main_module:
  name: main
  object: '../build/arm9.bin'
  hash: '15560e62cc17dc7a'
  delinks: delinks.txt
  symbols: symbols.txt
  relocations: relocs.txt
autoloads:
- kind: Itcm
  name: itcm
  object: '../build/itcm.bin'
  hash: deae433dc838b912
  delinks: itcm/delinks.txt
  symbols: itcm/symbols.txt
  relocations: itcm/relocs.txt
- kind: Dtcm
  name: dtcm
  object: '../build/dtcm.bin'
  hash: c6da5bb10005c16c
  delinks: dtcm/delinks.txt
  symbols: dtcm/symbols.txt
  relocations: dtcm/relocs.txt
overlays:
- id: 0
  name: ov000
  object: build/arm9_ov000.bin
  hash: '42f62ed35683d09b'
  delinks: overlays/ov000/delinks.txt
  symbols: overlays/ov000/symbols.txt
  relocations: overlays/ov000/relocs.txt
- id: 1
  name: ov001
  object: build/arm9_ov001.bin
  hash: cae2232b3313ae0b
  delinks: overlays/ov001/delinks.txt
  symbols: overlays/ov001/symbols.txt
  relocations: overlays/ov001/relocs.txt
- id: 2
  name: ov002
  object: build/arm9_ov002.bin
  hash: '2f9d1fb83bc53634'
  delinks: overlays/ov002/delinks.txt
  symbols: overlays/ov002/symbols.txt
  relocations: overlays/ov002/relocs.txt
- id: 3
  name: ov003
  object: build/arm9_ov003.bin
  hash: '23ea7bbd603d8111'
  delinks: overlays/ov003/delinks.txt
  symbols: overlays/ov003/symbols.txt
  relocations: overlays/ov003/relocs.txt
- id: 4
  name: ov004
  object: build/arm9_ov004.bin
  hash: b7ea8b56dae31ae8
  delinks: overlays/ov004/delinks.txt
  symbols: overlays/ov004/symbols.txt
  relocations: overlays/ov004/relocs.txt
- id: 5
  name: ov005
  object: build/arm9_ov005.bin
  hash: '9ce9aafd15562b50'
  delinks: overlays/ov005/delinks.txt
  symbols: overlays/ov005/symbols.txt
  relocations: overlays/ov005/relocs.txt
- id: 6
  name: ov006
  object: build/arm9_ov006.bin
  hash: '7d7adb3f5b119592'
  delinks: overlays/ov006/delinks.txt
  symbols: overlays/ov006/symbols.txt
  relocations: overlays/ov006/relocs.txt
- id: 7
  name: ov007
  object: build/arm9_ov007.bin
  hash: '20c53644839dfc04'
  delinks: overlays/ov007/delinks.txt
  symbols: overlays/ov007/symbols.txt
  relocations: overlays/ov007/relocs.txt
- id: 8
  name: ov008
  object: build/arm9_ov008.bin
  hash: df4e533cdd88100d
  delinks: overlays/ov008/delinks.txt
  symbols: overlays/ov008/symbols.txt
  relocations: overlays/ov008/relocs.txt
- id: 9
  name: ov009
  object: build/arm9_ov009.bin
  hash: '14bb3c9f6dbdb0af'
  delinks: overlays/ov009/delinks.txt
  symbols: overlays/ov009/symbols.txt
  relocations: overlays/ov009/relocs.txt
- id: 10
  name: ov010
  object: build/arm9_ov010.bin
  hash: d47011752298c6d3
  delinks: overlays/ov010/delinks.txt
  symbols: overlays/ov010/symbols.txt
  relocations: overlays/ov010/relocs.txt
- id: 11
  name: ov011
  object: build/arm9_ov011.bin
  hash: '54a3114d00032260'
  delinks: overlays/ov011/delinks.txt
  symbols: overlays/ov011/symbols.txt
  relocations: overlays/ov011/relocs.txt
- id: 12
  name: ov012
  object: build/arm9_ov012.bin
  hash: '7fb08d8eb6637ca9'
  delinks: overlays/ov012/delinks.txt
  symbols: overlays/ov012/symbols.txt
  relocations: overlays/ov012/relocs.txt
- id: 13
  name: ov013
  object: build/arm9_ov013.bin
  hash: '266a5d255aad24b6'
  delinks: overlays/ov013/delinks.txt
  symbols: overlays/ov013/symbols.txt
  relocations: overlays/ov013/relocs.txt
- id: 14
  name: ov014
  object: build/arm9_ov014.bin
  hash: '72ee2bb687c4b796'
  delinks: overlays/ov014/delinks.txt
  symbols: overlays/ov014/symbols.txt
  relocations: overlays/ov014/relocs.txt
- id: 15
  name: ov015
  object: build/arm9_ov015.bin
  hash: '36c3af3fec61dbea'
  delinks: overlays/ov015/delinks.txt
  symbols: overlays/ov015/symbols.txt
  relocations: overlays/ov015/relocs.txt
- id: 16
  name: ov016
  object: build/arm9_ov016.bin
  hash: e636ebf3b3f69531
  delinks: overlays/ov016/delinks.txt
  symbols: overlays/ov016/symbols.txt
  relocations: overlays/ov016/relocs.txt
- id: 17
  name: ov017
  object: build/arm9_ov017.bin
  hash: af2f119c0f4e88ee
  delinks: overlays/ov017/delinks.txt
  symbols: overlays/ov017/symbols.txt
  relocations: overlays/ov017/relocs.txt
- id: 18
  name: ov018
  object: build/arm9_ov018.bin
  hash: a2da1a5dfe59c82d
  delinks: overlays/ov018/delinks.txt
  symbols: overlays/ov018/symbols.txt
  relocations: overlays/ov018/relocs.txt
- id: 19
  name: ov019
  object: build/arm9_ov019.bin
  hash: '9abba002e50f481e'
  delinks: overlays/ov019/delinks.txt
  symbols: overlays/ov019/symbols.txt
  relocations: overlays/ov019/relocs.txt
- id: 20
  name: ov020
  object: build/arm9_ov020.bin
  hash: ff5849b3cc297e40
  delinks: overlays/ov020/delinks.txt
  symbols: overlays/ov020/symbols.txt
  relocations: overlays/ov020/relocs.txt
- id: 21
  name: ov021
  object: build/arm9_ov021.bin
  hash: '776f9858ba9fcf0a'
  delinks: overlays/ov021/delinks.txt
  symbols: overlays/ov021/symbols.txt
  relocations: overlays/ov021/relocs.txt
- id: 22
  name: ov022
  object: build/arm9_ov022.bin
  hash: '3af52df211289efa'
  delinks: overlays/ov022/delinks.txt
  symbols: overlays/ov022/symbols.txt
  relocations: overlays/ov022/relocs.txt
- id: 23
  name: ov023
  object: build/arm9_ov023.bin
  hash: f276c1efaf499c87
  delinks: overlays/ov023/delinks.txt
  symbols: overlays/ov023/symbols.txt
  relocations: overlays/ov023/relocs.txt
- id: 24
  name: ov024
  object: build/arm9_ov024.bin
  hash: '1416d4f373ffe240'
  delinks: overlays/ov024/delinks.txt
  symbols: overlays/ov024/symbols.txt
  relocations: overlays/ov024/relocs.txt
- id: 25
  name: ov025
  object: build/arm9_ov025.bin
  hash: b578d0aa1dd274af
  delinks: overlays/ov025/delinks.txt
  symbols: overlays/ov025/symbols.txt
  relocations: overlays/ov025/relocs.txt
- id: 26
  name: ov026
  object: build/arm9_ov026.bin
  hash: '3522f3d162458fd7'
  delinks: overlays/ov026/delinks.txt
  symbols: overlays/ov026/symbols.txt
  relocations: overlays/ov026/relocs.txt
- id: 27
  name: ov027
  object: build/arm9_ov027.bin
  hash: bd779eb25579ecc7
  delinks: overlays/ov027/delinks.txt
  symbols: overlays/ov027/symbols.txt
  relocations: overlays/ov027/relocs.txt
- id: 28
  name: ov028
  object: build/arm9_ov028.bin
  hash: '230e6f2cc942ef6d'
  delinks: overlays/ov028/delinks.txt
  symbols: overlays/ov028/symbols.txt
  relocations: overlays/ov028/relocs.txt
- id: 29
  name: ov029
  object: build/arm9_ov029.bin
  hash: bacbc1b27d723a42
  delinks: overlays/ov029/delinks.txt
  symbols: overlays/ov029/symbols.txt
  relocations: overlays/ov029/relocs.txt
- id: 30
  name: ov030
  object: build/arm9_ov030.bin
  hash: '043dc85a07c627bb'
  delinks: overlays/ov030/delinks.txt
  symbols: overlays/ov030/symbols.txt
  relocations: overlays/ov030/relocs.txt
- id: 31
  name: ov031
  object: build/arm9_ov031.bin
  hash: '2a4ec6b5a4afae49'
  delinks: overlays/ov031/delinks.txt
  symbols: overlays/ov031/symbols.txt
  relocations: overlays/ov031/relocs.txt
- id: 32
  name: ov032
  object: build/arm9_ov032.bin
  hash: e8a217a45ea2be94
  delinks: overlays/ov032/delinks.txt
  symbols: overlays/ov032/symbols.txt
  relocations: overlays/ov032/relocs.txt
- id: 33
  name: ov033
  object: build/arm9_ov033.bin
  hash: '933476ba3ea1ca5f'
  delinks: overlays/ov033/delinks.txt
  symbols: overlays/ov033/symbols.txt
  relocations: overlays/ov033/relocs.txt
- id: 34
  name: ov034
  object: build/arm9_ov034.bin
  hash: '9640abf184cd8329'
  delinks: overlays/ov034/delinks.txt
  symbols: overlays/ov034/symbols.txt
  relocations: overlays/ov034/relocs.txt
- id: 35
  name: ov035
  object: build/arm9_ov035.bin
  hash: eaad8e1854cb7713
  delinks: overlays/ov035/delinks.txt
  symbols: overlays/ov035/symbols.txt
  relocations: overlays/ov035/relocs.txt
- id: 36
  name: ov036
  object: build/arm9_ov036.bin
  hash: eee5833aef24c917
  delinks: overlays/ov036/delinks.txt
  symbols: overlays/ov036/symbols.txt
  relocations: overlays/ov036/relocs.txt
- id: 37
  name: ov037
  object: build/arm9_ov037.bin
  hash: '464a3d039f7584f1'
  delinks: overlays/ov037/delinks.txt
  symbols: overlays/ov037/symbols.txt
  relocations: overlays/ov037/relocs.txt
- id: 38
  name: ov038
  object: build/arm9_ov038.bin
  hash: b690ef93fecae894
  delinks: overlays/ov038/delinks.txt
  symbols: overlays/ov038/symbols.txt
  relocations: overlays/ov038/relocs.txt
- id: 39
  name: ov039
  object: build/arm9_ov039.bin
  hash: c3476a2337ff30b3
  delinks: overlays/ov039/delinks.txt
  symbols: overlays/ov039/symbols.txt
  relocations: overlays/ov039/relocs.txt
- id: 40
  name: ov040
  object: build/arm9_ov040.bin
  hash: '56010184add89f1c'
  delinks: overlays/ov040/delinks.txt
  symbols: overlays/ov040/symbols.txt
  relocations: overlays/ov040/relocs.txt
- id: 41
  name: ov041
  object: build/arm9_ov041.bin
  hash: '395dd1a373b90537'
  delinks: overlays/ov041/delinks.txt
  symbols: overlays/ov041/symbols.txt
  relocations: overlays/ov041/relocs.txt
- id: 42
  name: ov042
  object: build/arm9_ov042.bin
  hash: '507a1ac872dad44c'
  delinks: overlays/ov042/delinks.txt
  symbols: overlays/ov042/symbols.txt
  relocations: overlays/ov042/relocs.txt
- id: 43
  name: ov043
  object: build/arm9_ov043.bin
  hash: f28de0d44a096015
  delinks: overlays/ov043/delinks.txt
  symbols: overlays/ov043/symbols.txt
  relocations: overlays/ov043/relocs.txt
- id: 44
  name: ov044
  object: build/arm9_ov044.bin
  hash: '3dbf43168e293717'
  delinks: overlays/ov044/delinks.txt
  symbols: overlays/ov044/symbols.txt
  relocations: overlays/ov044/relocs.txt
- id: 45
  name: ov045
  object: build/arm9_ov045.bin
  hash: '83743817c4fd7f62'
  delinks: overlays/ov045/delinks.txt
  symbols: overlays/ov045/symbols.txt
  relocations: overlays/ov045/relocs.txt
- id: 46
  name: ov046
  object: build/arm9_ov046.bin
  hash: db0ed7f9c99ae92a
  delinks: overlays/ov046/delinks.txt
  symbols: overlays/ov046/symbols.txt
  relocations: overlays/ov046/relocs.txt
- id: 47
  name: ov047
  object: build/arm9_ov047.bin
  hash: d1d6edb744f6f19c
  delinks: overlays/ov047/delinks.txt
  symbols: overlays/ov047/symbols.txt
  relocations: overlays/ov047/relocs.txt
- id: 48
  name: ov048
  object: build/arm9_ov048.bin
  hash: a739435942388b34
  delinks: overlays/ov048/delinks.txt
  symbols: overlays/ov048/symbols.txt
  relocations: overlays/ov048/relocs.txt
- id: 49
  name: ov049
  object: build/arm9_ov049.bin
  hash: aa33c130201b4a2d
  delinks: overlays/ov049/delinks.txt
  symbols: overlays/ov049/symbols.txt
  relocations: overlays/ov049/relocs.txt
- id: 50
  name: ov050
  object: build/arm9_ov050.bin
  hash: '6e461c50689e7fcc'
  delinks: overlays/ov050/delinks.txt
  symbols: overlays/ov050/symbols.txt
  relocations: overlays/ov050/relocs.txt
- id: 51
  name: ov051
  object: build/arm9_ov051.bin
  hash: e3d9ebaa619fd074
  delinks: overlays/ov051/delinks.txt
  symbols: overlays/ov051/symbols.txt
  relocations: overlays/ov051/relocs.txt
- id: 52
  name: ov052
  object: build/arm9_ov052.bin
  hash: cc7dbc1277329a49
  delinks: overlays/ov052/delinks.txt
  symbols: overlays/ov052/symbols.txt
  relocations: overlays/ov052/relocs.txt
- id: 53
  name: ov053
  object: build/arm9_ov053.bin
  hash: '6055b5c9c0bbfedd'
  delinks: overlays/ov053/delinks.txt
  symbols: overlays/ov053/symbols.txt
  relocations: overlays/ov053/relocs.txt
- id: 54
  name: ov054
  object: build/arm9_ov054.bin
  hash: c83ca1f6c0a35d9f
  delinks: overlays/ov054/delinks.txt
  symbols: overlays/ov054/symbols.txt
  relocations: overlays/ov054/relocs.txt
- id: 55
  name: ov055
  object: build/arm9_ov055.bin
  hash: '0b3c31242b72f051'
  delinks: overlays/ov055/delinks.txt
  symbols: overlays/ov055/symbols.txt
  relocations: overlays/ov055/relocs.txt
- id: 56
  name: ov056
  object: build/arm9_ov056.bin
  hash: '1fe7cbe14c170f13'
  delinks: overlays/ov056/delinks.txt
  symbols: overlays/ov056/symbols.txt
  relocations: overlays/ov056/relocs.txt
- id: 57
  name: ov057
  object: build/arm9_ov057.bin
  hash: '75c8c7e84b6e0438'
  delinks: overlays/ov057/delinks.txt
  symbols: overlays/ov057/symbols.txt
  relocations: overlays/ov057/relocs.txt
- id: 58
  name: ov058
  object: build/arm9_ov058.bin
  hash: '07d1017d0511701e'
  delinks: overlays/ov058/delinks.txt
  symbols: overlays/ov058/symbols.txt
  relocations: overlays/ov058/relocs.txt
- id: 59
  name: ov059
  object: build/arm9_ov059.bin
  hash: a4ab223b7842c7d7
  delinks: overlays/ov059/delinks.txt
  symbols: overlays/ov059/symbols.txt
  relocations: overlays/ov059/relocs.txt
- id: 60
  name: ov060
  object: build/arm9_ov060.bin
  hash: '7b65cba0b7407728'
  delinks: overlays/ov060/delinks.txt
  symbols: overlays/ov060/symbols.txt
  relocations: overlays/ov060/relocs.txt
- id: 61
  name: ov061
  object: build/arm9_ov061.bin
  hash: '44139084df396b2b'
  delinks: overlays/ov061/delinks.txt
  symbols: overlays/ov061/symbols.txt
  relocations: overlays/ov061/relocs.txt
