rom_config: '../../../extract/eur/config.yaml'
main_module:
  name: main
  object: '../../../build/eur/build/arm9.bin'
  hash: c5177103015c4748
  delinks: delinks.txt
  symbols: symbols.txt
  relocations: relocs.txt
autoloads:
- kind: Itcm
  name: itcm
  object: '../../../build/eur/build/itcm.bin'
  hash: '85fe762332d6209f'
  delinks: itcm/delinks.txt
  symbols: itcm/symbols.txt
  relocations: itcm/relocs.txt
- kind: Dtcm
  name: dtcm
  object: '../../../build/eur/build/dtcm.bin'
  hash: c6da5bb10005c16c
  delinks: dtcm/delinks.txt
  symbols: dtcm/symbols.txt
  relocations: dtcm/relocs.txt
overlays:
- id: 0
  name: ov000
  object: '../../../build/eur/build/arm9_ov000.bin'
  hash: d0a3ce1360f8741a
  delinks: overlays/ov000/delinks.txt
  symbols: overlays/ov000/symbols.txt
  relocations: overlays/ov000/relocs.txt
- id: 1
  name: ov001
  object: '../../../build/eur/build/arm9_ov001.bin'
  hash: e61d5ca30d695b7b
  delinks: overlays/ov001/delinks.txt
  symbols: overlays/ov001/symbols.txt
  relocations: overlays/ov001/relocs.txt
- id: 2
  name: ov002
  object: '../../../build/eur/build/arm9_ov002.bin'
  hash: ac75c23a6dcc963e
  delinks: overlays/ov002/delinks.txt
  symbols: overlays/ov002/symbols.txt
  relocations: overlays/ov002/relocs.txt
- id: 3
  name: ov003
  object: '../../../build/eur/build/arm9_ov003.bin'
  hash: '1cc44be233a77b32'
  delinks: overlays/ov003/delinks.txt
  symbols: overlays/ov003/symbols.txt
  relocations: overlays/ov003/relocs.txt
- id: 4
  name: ov004
  object: '../../../build/eur/build/arm9_ov004.bin'
  hash: f790efa5fe78458a
  delinks: overlays/ov004/delinks.txt
  symbols: overlays/ov004/symbols.txt
  relocations: overlays/ov004/relocs.txt
- id: 5
  name: ov005
  object: '../../../build/eur/build/arm9_ov005.bin'
  hash: '4eaf6315c1cddad4'
  delinks: overlays/ov005/delinks.txt
  symbols: overlays/ov005/symbols.txt
  relocations: overlays/ov005/relocs.txt
- id: 6
  name: ov006
  object: '../../../build/eur/build/arm9_ov006.bin'
  hash: '5b191f40fe5a732b'
  delinks: overlays/ov006/delinks.txt
  symbols: overlays/ov006/symbols.txt
  relocations: overlays/ov006/relocs.txt
- id: 7
  name: ov007
  object: '../../../build/eur/build/arm9_ov007.bin'
  hash: '0abaaeb94e91672d'
  delinks: overlays/ov007/delinks.txt
  symbols: overlays/ov007/symbols.txt
  relocations: overlays/ov007/relocs.txt
- id: 8
  name: ov008
  object: '../../../build/eur/build/arm9_ov008.bin'
  hash: b9bd7133c759a676
  delinks: overlays/ov008/delinks.txt
  symbols: overlays/ov008/symbols.txt
  relocations: overlays/ov008/relocs.txt
- id: 9
  name: ov009
  object: '../../../build/eur/build/arm9_ov009.bin'
  hash: c8a5503d02444612
  delinks: overlays/ov009/delinks.txt
  symbols: overlays/ov009/symbols.txt
  relocations: overlays/ov009/relocs.txt
- id: 10
  name: ov010
  object: '../../../build/eur/build/arm9_ov010.bin'
  hash: fc5836029b0e0299
  delinks: overlays/ov010/delinks.txt
  symbols: overlays/ov010/symbols.txt
  relocations: overlays/ov010/relocs.txt
- id: 11
  name: ov011
  object: '../../../build/eur/build/arm9_ov011.bin'
  hash: '08c536aad54e40bd'
  delinks: overlays/ov011/delinks.txt
  symbols: overlays/ov011/symbols.txt
  relocations: overlays/ov011/relocs.txt
- id: 12
  name: ov012
  object: '../../../build/eur/build/arm9_ov012.bin'
  hash: '1b8fdc9ebf16f0bc'
  delinks: overlays/ov012/delinks.txt
  symbols: overlays/ov012/symbols.txt
  relocations: overlays/ov012/relocs.txt
- id: 13
  name: ov013
  object: '../../../build/eur/build/arm9_ov013.bin'
  hash: ca9ea1d61f54e400
  delinks: overlays/ov013/delinks.txt
  symbols: overlays/ov013/symbols.txt
  relocations: overlays/ov013/relocs.txt
- id: 14
  name: ov014
  object: '../../../build/eur/build/arm9_ov014.bin'
  hash: aca92acc0ac49b55
  delinks: overlays/ov014/delinks.txt
  symbols: overlays/ov014/symbols.txt
  relocations: overlays/ov014/relocs.txt
- id: 15
  name: ov015
  object: '../../../build/eur/build/arm9_ov015.bin'
  hash: '8c3f003095c0dbc0'
  delinks: overlays/ov015/delinks.txt
  symbols: overlays/ov015/symbols.txt
  relocations: overlays/ov015/relocs.txt
- id: 16
  name: ov016
  object: '../../../build/eur/build/arm9_ov016.bin'
  hash: ab9d59e3e825e1f7
  delinks: overlays/ov016/delinks.txt
  symbols: overlays/ov016/symbols.txt
  relocations: overlays/ov016/relocs.txt
- id: 17
  name: ov017
  object: '../../../build/eur/build/arm9_ov017.bin'
  hash: '2ca92cf745c066e1'
  delinks: overlays/ov017/delinks.txt
  symbols: overlays/ov017/symbols.txt
  relocations: overlays/ov017/relocs.txt
- id: 18
  name: ov018
  object: '../../../build/eur/build/arm9_ov018.bin'
  hash: b0d3302b78cbd0a6
  delinks: overlays/ov018/delinks.txt
  symbols: overlays/ov018/symbols.txt
  relocations: overlays/ov018/relocs.txt
- id: 19
  name: ov019
  object: '../../../build/eur/build/arm9_ov019.bin'
  hash: '103f80a748978f31'
  delinks: overlays/ov019/delinks.txt
  symbols: overlays/ov019/symbols.txt
  relocations: overlays/ov019/relocs.txt
- id: 20
  name: ov020
  object: '../../../build/eur/build/arm9_ov020.bin'
  hash: c0c6c39143b7588c
  delinks: overlays/ov020/delinks.txt
  symbols: overlays/ov020/symbols.txt
  relocations: overlays/ov020/relocs.txt
- id: 21
  name: ov021
  object: '../../../build/eur/build/arm9_ov021.bin'
  hash: '47240e5d83a23540'
  delinks: overlays/ov021/delinks.txt
  symbols: overlays/ov021/symbols.txt
  relocations: overlays/ov021/relocs.txt
- id: 22
  name: ov022
  object: '../../../build/eur/build/arm9_ov022.bin'
  hash: '696cbae30015b39a'
  delinks: overlays/ov022/delinks.txt
  symbols: overlays/ov022/symbols.txt
  relocations: overlays/ov022/relocs.txt
- id: 23
  name: ov023
  object: '../../../build/eur/build/arm9_ov023.bin'
  hash: '0c1f10b74cf644c0'
  delinks: overlays/ov023/delinks.txt
  symbols: overlays/ov023/symbols.txt
  relocations: overlays/ov023/relocs.txt
- id: 24
  name: ov024
  object: '../../../build/eur/build/arm9_ov024.bin'
  hash: '9c7955e706e5a8d4'
  delinks: overlays/ov024/delinks.txt
  symbols: overlays/ov024/symbols.txt
  relocations: overlays/ov024/relocs.txt
- id: 25
  name: ov025
  object: '../../../build/eur/build/arm9_ov025.bin'
  hash: '21ef0909af229529'
  delinks: overlays/ov025/delinks.txt
  symbols: overlays/ov025/symbols.txt
  relocations: overlays/ov025/relocs.txt
- id: 26
  name: ov026
  object: '../../../build/eur/build/arm9_ov026.bin'
  hash: d0c781280a39026f
  delinks: overlays/ov026/delinks.txt
  symbols: overlays/ov026/symbols.txt
  relocations: overlays/ov026/relocs.txt
- id: 27
  name: ov027
  object: '../../../build/eur/build/arm9_ov027.bin'
  hash: b1f030b89f7f0670
  delinks: overlays/ov027/delinks.txt
  symbols: overlays/ov027/symbols.txt
  relocations: overlays/ov027/relocs.txt
- id: 28
  name: ov028
  object: '../../../build/eur/build/arm9_ov028.bin'
  hash: ec24d27996d526d8
  delinks: overlays/ov028/delinks.txt
  symbols: overlays/ov028/symbols.txt
  relocations: overlays/ov028/relocs.txt
- id: 29
  name: ov029
  object: '../../../build/eur/build/arm9_ov029.bin'
  hash: '427bb9ee759b171d'
  delinks: overlays/ov029/delinks.txt
  symbols: overlays/ov029/symbols.txt
  relocations: overlays/ov029/relocs.txt
- id: 30
  name: ov030
  object: '../../../build/eur/build/arm9_ov030.bin'
  hash: f5595c9486b96277
  delinks: overlays/ov030/delinks.txt
  symbols: overlays/ov030/symbols.txt
  relocations: overlays/ov030/relocs.txt
- id: 31
  name: ov031
  object: '../../../build/eur/build/arm9_ov031.bin'
  hash: '82cee2a51a6f33d2'
  delinks: overlays/ov031/delinks.txt
  symbols: overlays/ov031/symbols.txt
  relocations: overlays/ov031/relocs.txt
- id: 32
  name: ov032
  object: '../../../build/eur/build/arm9_ov032.bin'
  hash: '5ef6a50d33f04e6e'
  delinks: overlays/ov032/delinks.txt
  symbols: overlays/ov032/symbols.txt
  relocations: overlays/ov032/relocs.txt
- id: 33
  name: ov033
  object: '../../../build/eur/build/arm9_ov033.bin'
  hash: '96c42cb799be89b8'
  delinks: overlays/ov033/delinks.txt
  symbols: overlays/ov033/symbols.txt
  relocations: overlays/ov033/relocs.txt
- id: 34
  name: ov034
  object: '../../../build/eur/build/arm9_ov034.bin'
  hash: '1c835859b5222946'
  delinks: overlays/ov034/delinks.txt
  symbols: overlays/ov034/symbols.txt
  relocations: overlays/ov034/relocs.txt
- id: 35
  name: ov035
  object: '../../../build/eur/build/arm9_ov035.bin'
  hash: '47fc7f1bcd462458'
  delinks: overlays/ov035/delinks.txt
  symbols: overlays/ov035/symbols.txt
  relocations: overlays/ov035/relocs.txt
- id: 36
  name: ov036
  object: '../../../build/eur/build/arm9_ov036.bin'
  hash: '0efa2cb107874369'
  delinks: overlays/ov036/delinks.txt
  symbols: overlays/ov036/symbols.txt
  relocations: overlays/ov036/relocs.txt
- id: 37
  name: ov037
  object: '../../../build/eur/build/arm9_ov037.bin'
  hash: '731135f4f129de0a'
  delinks: overlays/ov037/delinks.txt
  symbols: overlays/ov037/symbols.txt
  relocations: overlays/ov037/relocs.txt
- id: 38
  name: ov038
  object: '../../../build/eur/build/arm9_ov038.bin'
  hash: '2de85d0439e49af3'
  delinks: overlays/ov038/delinks.txt
  symbols: overlays/ov038/symbols.txt
  relocations: overlays/ov038/relocs.txt
- id: 39
  name: ov039
  object: '../../../build/eur/build/arm9_ov039.bin'
  hash: '9615e0c7d830cafc'
  delinks: overlays/ov039/delinks.txt
  symbols: overlays/ov039/symbols.txt
  relocations: overlays/ov039/relocs.txt
- id: 40
  name: ov040
  object: '../../../build/eur/build/arm9_ov040.bin'
  hash: f923143c47b73ca1
  delinks: overlays/ov040/delinks.txt
  symbols: overlays/ov040/symbols.txt
  relocations: overlays/ov040/relocs.txt
- id: 41
  name: ov041
  object: '../../../build/eur/build/arm9_ov041.bin'
  hash: '379f73698699f2cd'
  delinks: overlays/ov041/delinks.txt
  symbols: overlays/ov041/symbols.txt
  relocations: overlays/ov041/relocs.txt
- id: 42
  name: ov042
  object: '../../../build/eur/build/arm9_ov042.bin'
  hash: '6b5f21ab76cf10ba'
  delinks: overlays/ov042/delinks.txt
  symbols: overlays/ov042/symbols.txt
  relocations: overlays/ov042/relocs.txt
- id: 43
  name: ov043
  object: '../../../build/eur/build/arm9_ov043.bin'
  hash: '444750745e25de2a'
  delinks: overlays/ov043/delinks.txt
  symbols: overlays/ov043/symbols.txt
  relocations: overlays/ov043/relocs.txt
- id: 44
  name: ov044
  object: '../../../build/eur/build/arm9_ov044.bin'
  hash: '1e4d5aeb11cddb4e'
  delinks: overlays/ov044/delinks.txt
  symbols: overlays/ov044/symbols.txt
  relocations: overlays/ov044/relocs.txt
- id: 45
  name: ov045
  object: '../../../build/eur/build/arm9_ov045.bin'
  hash: '9ceab392f06fd4fe'
  delinks: overlays/ov045/delinks.txt
  symbols: overlays/ov045/symbols.txt
  relocations: overlays/ov045/relocs.txt
- id: 46
  name: ov046
  object: '../../../build/eur/build/arm9_ov046.bin'
  hash: '09b721b5f394d12a'
  delinks: overlays/ov046/delinks.txt
  symbols: overlays/ov046/symbols.txt
  relocations: overlays/ov046/relocs.txt
- id: 47
  name: ov047
  object: '../../../build/eur/build/arm9_ov047.bin'
  hash: '654818d001f29338'
  delinks: overlays/ov047/delinks.txt
  symbols: overlays/ov047/symbols.txt
  relocations: overlays/ov047/relocs.txt
- id: 48
  name: ov048
  object: '../../../build/eur/build/arm9_ov048.bin'
  hash: '4a1ab467ec2c96bc'
  delinks: overlays/ov048/delinks.txt
  symbols: overlays/ov048/symbols.txt
  relocations: overlays/ov048/relocs.txt
- id: 49
  name: ov049
  object: '../../../build/eur/build/arm9_ov049.bin'
  hash: '374ac9a7cd22eaa8'
  delinks: overlays/ov049/delinks.txt
  symbols: overlays/ov049/symbols.txt
  relocations: overlays/ov049/relocs.txt
- id: 50
  name: ov050
  object: '../../../build/eur/build/arm9_ov050.bin'
  hash: '8f28325b5e76e020'
  delinks: overlays/ov050/delinks.txt
  symbols: overlays/ov050/symbols.txt
  relocations: overlays/ov050/relocs.txt
- id: 51
  name: ov051
  object: '../../../build/eur/build/arm9_ov051.bin'
  hash: '508bad1a3a9de314'
  delinks: overlays/ov051/delinks.txt
  symbols: overlays/ov051/symbols.txt
  relocations: overlays/ov051/relocs.txt
- id: 52
  name: ov052
  object: '../../../build/eur/build/arm9_ov052.bin'
  hash: '9253547a789ca015'
  delinks: overlays/ov052/delinks.txt
  symbols: overlays/ov052/symbols.txt
  relocations: overlays/ov052/relocs.txt
- id: 53
  name: ov053
  object: '../../../build/eur/build/arm9_ov053.bin'
  hash: '6d7e51471cd51846'
  delinks: overlays/ov053/delinks.txt
  symbols: overlays/ov053/symbols.txt
  relocations: overlays/ov053/relocs.txt
- id: 54
  name: ov054
  object: '../../../build/eur/build/arm9_ov054.bin'
  hash: f590a2229ad45c04
  delinks: overlays/ov054/delinks.txt
  symbols: overlays/ov054/symbols.txt
  relocations: overlays/ov054/relocs.txt
- id: 55
  name: ov055
  object: '../../../build/eur/build/arm9_ov055.bin'
  hash: b5a4673cf74bb33d
  delinks: overlays/ov055/delinks.txt
  symbols: overlays/ov055/symbols.txt
  relocations: overlays/ov055/relocs.txt
- id: 56
  name: ov056
  object: '../../../build/eur/build/arm9_ov056.bin'
  hash: '54fef0b4820bc440'
  delinks: overlays/ov056/delinks.txt
  symbols: overlays/ov056/symbols.txt
  relocations: overlays/ov056/relocs.txt
- id: 57
  name: ov057
  object: '../../../build/eur/build/arm9_ov057.bin'
  hash: f32671d4ba42e474
  delinks: overlays/ov057/delinks.txt
  symbols: overlays/ov057/symbols.txt
  relocations: overlays/ov057/relocs.txt
- id: 58
  name: ov058
  object: '../../../build/eur/build/arm9_ov058.bin'
  hash: '2b9021433ec25bb4'
  delinks: overlays/ov058/delinks.txt
  symbols: overlays/ov058/symbols.txt
  relocations: overlays/ov058/relocs.txt
- id: 59
  name: ov059
  object: '../../../build/eur/build/arm9_ov059.bin'
  hash: '6defdcafa36dffb5'
  delinks: overlays/ov059/delinks.txt
  symbols: overlays/ov059/symbols.txt
  relocations: overlays/ov059/relocs.txt
- id: 60
  name: ov060
  object: '../../../build/eur/build/arm9_ov060.bin'
  hash: '1ff414f226a25d84'
  delinks: overlays/ov060/delinks.txt
  symbols: overlays/ov060/symbols.txt
  relocations: overlays/ov060/relocs.txt
- id: 61
  name: ov061
  object: '../../../build/eur/build/arm9_ov061.bin'
  hash: c9da539bdd0b2bd3
  delinks: overlays/ov061/delinks.txt
  symbols: overlays/ov061/symbols.txt
  relocations: overlays/ov061/relocs.txt
